#! /bin/bash

daily_note="$(date +%d-%b-%Y).md"

cd ~/Notes/DailyNotes/

if [[ ! -f $daily_note ]]; then
  touch $daily_note
fi

if [[ -z $TMUX ]]; then
  nvim $daily_note
else
  tmux neww -n "daily_note" nvim $daily_note
fi
