#!/bin/bash

selected=$(find -L ~/.config -mindepth 1 -maxdepth 1 -type d \
  | sed "s|$HOME/.config/||" \
  |fzf --reverse --preview 'ls ~/.config/{}')

if [[ -z $selected ]]; then
  exit 0
fi

window_name=$(basename $selected | tr " " "_")

selectfile=$(find -L ~/.config/$selected -mindepth 1 -maxdepth 1 \
  | sed "s|$HOME/.config/$selected/||" \
  | fzf --reverse --preview "cat ~/.config/"$selected"/{}")

if [[ -z $selectfile ]]; then
  exit 0
fi

selectfile="$HOME/.config/$selected/$selectfile"

cd "$HOME/.config/$selected"

if [[ -z $TMUX ]]; then
  nvim $selectfile
else
  tmux neww -n $window_name nvim $selectfile
fi
