#! /bin/bash

cd "$HOME/Notes/Movies/"

movie_file="MovieList.md"

if [[ -f "$movie_file" ]]; then
  touch "$movie_file"
fi

if [[ -z $TMUX ]]; then
  nvim "$movie_file"
  exit 0
fi

tmux split-window -h -l 30% nvim $movie_file
