#!/bin/bash

EDITOR="nvim"

cd $(tmux display-message -p "#{pane_current_path}")

GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

if [ -z "$GIT_ROOT" ]; then
  echo "The fuck you doing"
  exit 0
fi

NOTE_FILENAME="$(basename $GIT_ROOT).md"

NOTE_FILE="$HOME/Notes/Projects/$NOTE_FILENAME"

if [ ! -f "$NOTE_FILE" ]; then
    touch "$NOTE_FILE"
fi

if [[ -z $TMUX ]]; then
  $EDITOR "$NOTE_FILE"
else
  tmux split-window -h -l 87 $EDITOR "$NOTE_FILE"
fi

