#! /bin/bash

project=$(find ~/Documents/Projects/ -mindepth 1 -maxdepth 1 -type d \
  | sed "s|$HOME/Documents/Projects/||" \
  | fzf --print-query \
  | tail -n1 )

if [[ -z $project ]]; then
  exit 0
fi

project_dir="$HOME/Documents/Projects/$project"

if [[ ! -d "$project_dir" ]]; then
  read -rp "Create new project? [y/N] " userinput
  if [[ ! "$userinput" =~ ^[yY]$ ]]; then
    exit 0
  fi
  mkdir "$project_dir"
fi

if ! tmux has-session -t "$project" 2>/dev/null; then
  tmux new-session -ds "$project" -c "$project_dir"
fi

if [[ -z $TMUX ]]; then
  tmux attach-session -t "$project"
else
  tmux switch-client -t "$project"
fi
