#! /bin/bash

cd ~/Notes/

todo_file="TODO.md"

if [[ ! -f "$todo_file" ]]; then
  touch $todo_file
fi

if [[ -z $TMUX ]]; then
  nvim $todo_file
else
  tmux split-window -h -l 30% nvim $todo_file
fi
