#! /bin/bash

cd ~/notes/02_Areas/TODO/

todo_file="TODO.md"

if [[ ! -f "$todo_file" ]]; then
  touch $todo_file
fi

if [[ -z $TMUX ]]; then
  nvim $todo_file
else
  tmux neww -n "todo" nvim $todo_file
fi
